[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/AstroNvim/AstroNvim"
    # TODO upgrade to v4
    clone.args = ["--depth", "1", "--branch", "v3.45.3"]
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    clone.args = ["--depth", "1"]
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    clone.args = ["--depth", "1"]
    exact = true
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    clone.args = ["--depth", "1"]
    exact = true
    refreshPeriod = "168h"
[".local/share/fonts/UbuntuMonoNerdFont-Regular.ttf"] # Used by Alacritty
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFont-Regular.ttf"
    refreshPeriod = "168h"
