enable_audio_bell no

tab_bar_edge top
tab_bar_style powerline

map ctrl+shift+left no_op
map ctrl+shift+right no_op
map ctrl+page_up next_tab
map ctrl+page_down previous_tab

remember_window_size no
initial_window_width 100c
initial_window_height 30c
