#################################
#             Shadows           #
#################################

# Enabled client-side shadows on windows. Note desktop windows 
# (windows with '_NET_WM_WINDOW_TYPE_DESKTOP') never get shadow, 
# unless explicitly requested using the wintypes option.
shadow = true;
shadow-opacity = 0.75;
shadow-radius = 12;
shadow-offset-x = -8;
shadow-offset-y = -8;

shadow-exclude = [
  "class_g = 'i3-frame'",
  # https://wiki.archlinux.org/title/Picom#Tabbed_windows_(shadows_and_transparency)
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.05;
fade-out-step = 0.025;
fade-delta = 3;

# fade-exclude = [];
# no-fading-openclose = false;

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 0.95;
# menu-opacity = 1.0;
# active-opacity = 1.0;
inactive-dim = 0.25;

focus-exclude = [
  "class_g = 'i3-frame'"
];

#################################
#       General Settings        #
#################################

backend = "glx";
vsync = true;

mark-ovredir-focused = true;
detect-rounded-corners = true;
# detect-client-opacity = false;
use-ewmh-active-win = false;
detect-transient = true;
detect-client-leader = true;
render-sync-fence = true

log-level = "warn";

wintypes:
{
  dock = { shadow = false; }
};
